---
- name: Basic settings
  hosts: localhost
  tasks:
    - name: Set VI mode
      lineinfile:
        dest: /etc/bash.bashrc
        regexp: "set -o vi"
        line: "set -o vi"

- include: vimrc.yml
- include: ansible-galaxy.yml
- include: docker.yml
